// =============================================================================
// Skillstat AI - Admin Portal State & Data Store
// Multi-Department Catalog with Real Video Lessons & Administrative Store
// =============================================================================

export const initialDepartments = [
  {
    id: 'dept-health',
    name: 'Health & Family Welfare Statistics',
    code: 'HFW-STAT',
    head: 'Dr. Sunita Deshmukh, Director of Health Analytics',
    description: 'Epidemiological tracking, hospital registers, clinical research, biostatistics, and public health surveys.',
    employeeCount: 24,
  },
  {
    id: 'dept-agri',
    name: 'Agriculture & Farmers Welfare Statistics',
    code: 'AGRI-STAT',
    head: 'Dr. Rameshwar Rao, Nodal Agronomist',
    description: 'Crop yield estimation, area enumeration, agricultural census, soil health data, and rural commodity pricing.',
    employeeCount: 32,
  },
  {
    id: 'dept-nso',
    name: 'National Statistical Office (NSO)',
    code: 'NSO-CENTRAL',
    head: 'Shri Arvind K. Verma, Additional Director General',
    description: 'Nationwide sample surveys, National Accounts compilation, official classifications, and statistical standards.',
    employeeCount: 48,
  },
  {
    id: 'dept-price',
    name: 'Price & Consumer Statistics',
    code: 'PCS-DIV',
    head: 'Smt. Malini Sen, Chief Economic Adviser',
    description: 'Consumer Price Index (CPI), Wholesale Price Index (WPI), market intelligence, and inflation monitoring.',
    employeeCount: 18,
  },
  {
    id: 'dept-tech',
    name: 'Technology, AI & Data Science Directorate',
    code: 'TECH-AI',
    head: 'Vikramaditya Roy, Chief Technology Officer',
    description: 'Public data platform engineering, automated ETL pipelines, AI/ML models, cloud infrastructure, and cybersecurity.',
    employeeCount: 29,
  },
  {
    id: 'dept-labour',
    name: 'Labour & Employment Statistics',
    code: 'LES-WING',
    head: 'Pradeep K. Nayak, Deputy Director General',
    description: 'Periodic Labour Force Survey (PLFS), occupational wage surveys, employment registers, and workforce analytics.',
    employeeCount: 15,
  },
  {
    id: 'dept-industry',
    name: 'Industrial & Manufacturing Statistics',
    code: 'IMS-DIV',
    head: 'Rajeev Singhania, Director of Industrial Studies',
    description: 'Index of Industrial Production (IIP), Annual Survey of Industries (ASI), and factory output analysis.',
    employeeCount: 19,
  },
  {
    id: 'dept-state',
    name: 'State Directorates of Economics & Statistics',
    code: 'DES-STATE',
    head: 'Regional Coordination Council',
    description: 'Sub-national economic accounting, district level statistics, state sample pooling, and regional monitoring.',
    employeeCount: 36,
  },
]

export const initialCourses = [
  // --- HEALTH & FAMILY WELFARE ---
  {
    id: 'crs-health-01',
    title: 'Epidemiological Surveillance & Public Health Statistics',
    provider: 'iGOT Karmayogi / MoHFW',
    department: 'Health & Family Welfare Statistics',
    role: 'Doctor',
    competency: 'Epidemiology',
    skills: ['Medical research', 'Patient care', 'Clinical documentation', 'Data analysis'],
    duration: '10 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/1JZG9x_VOwA',
    description: 'Core concepts in disease surveillance, incidence/prevalence metrics, outbreak response models, and clinical data governance.',
    outcomes: [
      'Interpret communicable and non-communicable disease incidence rates accurately',
      'Deploy standardized clinical registries adhering to ICMR & WHO protocol',
      'Formulate evidence-based clinical intervention policies from surveillance metrics',
    ],
    status: 'Active',
    enrolledCount: 14,
    rating: 4.9,
  },
  {
    id: 'crs-health-02',
    title: 'Biostatistics, Clinical Trials & Healthcare Quality',
    provider: 'National Institute of Health & Family Welfare (NIHFW)',
    department: 'Health & Family Welfare Statistics',
    role: 'Senior Medical Officer',
    competency: 'Biostatistics',
    skills: ['Medical research', 'Statistical analysis', 'Health and safety', 'Clinical documentation'],
    duration: '12 Hours',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube-nocookie.com/embed/5a3vWn_zVPo',
    description: 'Biostatistical design of randomized control trials, hypothesis testing in clinical cohorts, survival analysis, and NABH standards.',
    outcomes: [
      'Calculate statistical sample sizes for clinical research trials',
      'Execute Kaplan-Meier survival curves and odds ratio modeling',
      'Establish hospital quality indicator dashboards conforming to NABH standards',
    ],
    status: 'Active',
    enrolledCount: 9,
    rating: 4.8,
  },

  // --- AGRICULTURE & FARMERS WELFARE ---
  {
    id: 'crs-agri-01',
    title: 'Crop Yield Modeling, Sampling & Agro-Statistics',
    provider: 'Indian Council of Agricultural Research (ICAR) / iGOT',
    department: 'Agriculture & Farmers Welfare Statistics',
    role: 'Agricultural Statistics Officer',
    competency: 'Agricultural Statistics',
    skills: ['Sampling', 'Crop Yield Estimation', 'Survey Design', 'Data analysis'],
    duration: '14 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/3y_K_fJ9c-8',
    description: 'Field sampling methods for General Crop Estimation Surveys (GCES), crop-cutting experiments, and agro-climatic yield variance models.',
    outcomes: [
      'Design stratified multistage crop-cutting experiment grids',
      'Estimate district-level yield forecasts with confidence intervals under 3%',
      'Integrate weather station rainfall data into seasonal harvest projections',
    ],
    status: 'Active',
    enrolledCount: 22,
    rating: 4.9,
  },
  {
    id: 'crs-agri-02',
    title: 'Geospatial Remote Sensing in Agricultural Enumeration',
    provider: 'Indian Institute of Remote Sensing (IIRS) / DES',
    department: 'Agriculture & Farmers Welfare Statistics',
    role: 'Survey Officer',
    competency: 'GIS',
    skills: ['GIS', 'Spatial analysis', 'Research', 'Excel'],
    duration: '8 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/5kL_6Fp3z9s',
    description: 'Satellite NDVI spectral indices, land-use classification, and GIS-based drought assessment for agricultural reporting.',
    outcomes: [
      'Extract NDVI vegetation health indices from Sentinel satellite imagery',
      'Delineate crop area boundaries with polygon geo-tagging tools',
      'Produce automated crop acreage maps for seasonal government reports',
    ],
    status: 'Active',
    enrolledCount: 18,
    rating: 4.7,
  },

  // --- TECHNOLOGY & DATA SCIENCE ---
  {
    id: 'crs-tech-01',
    title: 'Python for Public Data Science, ETL & Automated Pipelines',
    provider: 'Ministry of Electronics & IT (MeitY) / CBC',
    department: 'Technology, AI & Data Science Directorate',
    role: 'Data Scientist',
    competency: 'Python',
    skills: ['Python', 'Data analysis', 'SQL', 'Machine learning', 'APIs'],
    duration: '16 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/rfscVS0vtbw',
    description: 'Complete programmatic data transformation with Pandas, NumPy, automated API ingestors, and data validation routines.',
    outcomes: [
      'Build end-to-end reproducible data pipelines with Python and Pandas',
      'Automate monthly administrative data aggregation and anomaly flags',
      'Deploy REST APIs serving validated statistical data cubes to internal dashboards',
    ],
    status: 'Active',
    enrolledCount: 35,
    rating: 5.0,
  },
  {
    id: 'crs-tech-02',
    title: 'Applied Machine Learning & Predictive Modeling for Governance',
    provider: 'Capacity Building Commission (CBC)',
    department: 'Technology, AI & Data Science Directorate',
    role: 'Data Analyst',
    competency: 'AI/ML',
    skills: ['Machine learning', 'Statistical analysis', 'Python', 'Critical thinking'],
    duration: '12 Hours',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube-nocookie.com/embed/i_LwzRVP7bg',
    description: 'Supervised classification, regression modeling, feature engineering, and model interpretability (SHAP) for public policy.',
    outcomes: [
      'Train supervised learning models on large public administrative registries',
      'Evaluate model fairness, precision-recall trade-offs, and ROC-AUC metrics',
      'Interpret feature importance using SHAP values for transparent policy decisions',
    ],
    status: 'Active',
    enrolledCount: 28,
    rating: 4.9,
  },
  {
    id: 'crs-tech-03',
    title: 'Advanced SQL, Relational Architecture & Query Optimization',
    provider: 'National Informatics Centre (NIC)',
    department: 'Technology, AI & Data Science Directorate',
    role: 'Database Administrator',
    competency: 'SQL',
    skills: ['SQL', 'Database management', 'System architecture', 'Troubleshooting'],
    duration: '8 Hours',
    difficulty: 'Foundational to Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/HXV3zeRR3h4',
    description: 'Master relational schema design, complex window functions, CTEs, indexing strategies, and multi-table joins.',
    outcomes: [
      'Execute high-speed analytical queries using CTEs and window partition functions',
      'Optimize database execution plans to reduce query latency on massive registries',
      'Implement atomic transactions and role-based data access security',
    ],
    status: 'Active',
    enrolledCount: 30,
    rating: 4.8,
  },

  // --- NATIONAL STATISTICAL OFFICE (NSO) ---
  {
    id: 'crs-nso-01',
    title: 'Official Statistics Fundamentals & National Quality Frameworks',
    provider: 'National Statistical Systems Training Academy (NSSTA) / MoSPI',
    department: 'National Statistical Office (NSO)',
    role: 'Statistical Officer',
    competency: 'Official Statistics',
    skills: ['Official Statistics', 'Sampling', 'Survey Design', 'Data Quality Frameworks'],
    duration: '12 Hours',
    difficulty: 'Foundational',
    videoUrl: 'https://www.youtube-nocookie.com/embed/Xzc4zP3bT8o',
    description: 'United Nations Fundamental Principles of Official Statistics, National Quality Assurance Framework (NQAF), and survey design.',
    outcomes: [
      'Apply UN-NQAF data audit standards to national survey microdata',
      'Formulate stratified random sampling strategies with proper sampling weights',
      'Publish standardized metadata documentation conforming to SDMX formats',
    ],
    status: 'Active',
    enrolledCount: 42,
    rating: 4.9,
  },
  {
    id: 'crs-nso-02',
    title: 'Advanced Survey Methodology & Non-Sampling Error Control',
    provider: 'NSSTA Workshop / TPAC',
    department: 'National Statistical Office (NSO)',
    role: 'Senior Statistical Officer',
    competency: 'Survey Design',
    skills: ['Survey Design', 'Sampling', 'Data Quality Frameworks', 'Critical thinking'],
    duration: '10 Hours',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube-nocookie.com/embed/UnyS3c4WfT8',
    description: 'Imputation techniques for missing data, respondent burden reduction, questionnaire pre-testing, and non-response bias adjustments.',
    outcomes: [
      'Implement hot-deck and regression imputation for survey item non-response',
      'Detect and correct interviewer variance in large-scale household schedules',
      'Calculate effective sample size adjustments accounting for design effects (DEFF)',
    ],
    status: 'Active',
    enrolledCount: 25,
    rating: 4.8,
  },

  // --- PRICE & CONSUMER STATISTICS ---
  {
    id: 'crs-price-01',
    title: 'Consumer Price Index (CPI) Compilation & Laspeyres Indices',
    provider: 'Central Statistics Office (CSO) / DoPT',
    department: 'Price & Consumer Statistics',
    role: 'Price Statistics Officer',
    competency: 'Price Statistics',
    skills: ['Financial analysis', 'Excel', 'Statistical analysis', 'Reporting'],
    duration: '8 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/r_e0Q8yH2wQ',
    description: 'Methodology of CPI (Rural, Urban, Combined), basket weighting, geometric mean item aggregation, and substitution bias controls.',
    outcomes: [
      'Compute modified Laspeyres price indices using current quotation registries',
      'Perform seasonal price adjustments on volatile food and commodity groups',
      'Draft monthly headline inflation reports with core inflation breakdowns',
    ],
    status: 'Active',
    enrolledCount: 16,
    rating: 4.9,
  },
  {
    id: 'crs-price-02',
    title: 'Macroeconomic Accounts, GDP Estimation & Fiscal Tracking',
    provider: 'Capacity Building Commission (CBC) / NITI Aayog',
    department: 'Price & Consumer Statistics',
    role: 'Economist',
    competency: 'Macroeconomics',
    skills: ['Financial analysis', 'Budgeting', 'Analytical thinking', 'Research'],
    duration: '11 Hours',
    difficulty: 'Advanced',
    videoUrl: 'https://www.youtube-nocookie.com/embed/1Il5IQEkCO0',
    description: 'System of National Accounts (SNA 2008), gross value added (GVA) by economic activity, and fiscal multiplier estimation.',
    outcomes: [
      'Calculate quarterly GVA across primary, secondary, and tertiary sectors',
      'Reconcile production approach vs. expenditure approach discrepancies in GDP',
      'Construct econometric input-output matrices for economic impact forecasting',
    ],
    status: 'Active',
    enrolledCount: 19,
    rating: 4.9,
  },

  // --- LABOUR & EMPLOYMENT STATISTICS ---
  {
    id: 'crs-labour-01',
    title: 'Labour Market Metrics & Periodic Labour Force Survey (PLFS)',
    provider: 'V. V. Giri National Labour Institute / MoSPI',
    department: 'Labour & Employment Statistics',
    role: 'Labour Statistics Officer',
    competency: 'Labour Statistics',
    skills: ['Data analysis', 'Survey Design', 'Reporting', 'Excel'],
    duration: '9 Hours',
    difficulty: 'Intermediate',
    videoUrl: 'https://www.youtube-nocookie.com/embed/U3l_xX4uH6M',
    description: 'Worker Population Ratio (WPR), Labour Force Participation Rate (LFPR), Usual Status vs. CWS activity measurements, and informal sector tracking.',
    outcomes: [
      'Calculate accurate LFPR and Unemployment Rate under Current Weekly Status (CWS)',
      'Analyze gender-disaggregated workforce participation across rural and urban cadres',
      'Compile quarterly employment bulletins from rotational panel sample data',
    ],
    status: 'Active',
    enrolledCount: 12,
    rating: 4.7,
  },

  // --- ALL DEPARTMENTS / GENERAL LEADERSHIP & GOVERNANCE ---
  {
    id: 'crs-gov-01',
    title: 'Digital Data Governance & DPDP Statutory Compliance',
    provider: 'Department of Personnel and Training (DoPT)',
    department: 'All Departments',
    role: 'All Roles',
    competency: 'Digital Governance',
    skills: ['Data Privacy', 'Digital Governance', 'Compliance', 'Documentation'],
    duration: '6 Hours',
    difficulty: 'Foundational',
    videoUrl: 'https://www.youtube-nocookie.com/embed/rfscVS0vtbw',
    description: 'Digital Personal Data Protection (DPDP) Act norms, cryptographic anonymization, consent management, and data audit security in government.',
    outcomes: [
      'Implement data minimization and anonymization techniques on citizen registers',
      'Formulate statutory compliance checklists under current DPDP guidelines',
      'Mitigate confidential disclosure risks when publishing public microdata',
    ],
    status: 'Active',
    enrolledCount: 55,
    rating: 4.9,
  },
]

export const initialSkillGaps = [
  {
    skill: 'Epidemiology & Clinical Registries',
    domain: 'Clinical Competencies',
    department: 'Health & Family Welfare Statistics',
    employeesDeficient: 8,
    avgProficiency: 52,
    targetBenchmark: 80,
    gap: 28,
    priority: 'Critical',
  },
  {
    skill: 'Crop Yield Forecasting Models',
    domain: 'Agricultural Analytics',
    department: 'Agriculture & Farmers Welfare Statistics',
    employeesDeficient: 11,
    avgProficiency: 58,
    targetBenchmark: 80,
    gap: 22,
    priority: 'Moderate',
  },
  {
    skill: 'Python Automated Data Pipelines',
    domain: 'Technical Competencies',
    department: 'Technology, AI & Data Science Directorate',
    employeesDeficient: 14,
    avgProficiency: 44,
    targetBenchmark: 80,
    gap: 36,
    priority: 'Critical',
  },
  {
    skill: 'Consumer Price Index Methodology',
    domain: 'Economic Competencies',
    department: 'Price & Consumer Statistics',
    employeesDeficient: 6,
    avgProficiency: 62,
    targetBenchmark: 80,
    gap: 18,
    priority: 'Moderate',
  },
  {
    skill: 'Official Statistics Sampling & NQAF',
    domain: 'Statistical Competencies',
    department: 'National Statistical Office (NSO)',
    employeesDeficient: 9,
    avgProficiency: 51,
    targetBenchmark: 80,
    gap: 29,
    priority: 'Critical',
  },
]

export const initialEmployees = [
  {
    id: 'emp-201',
    name: 'Dr. Anita Joshi',
    email: 'anita.joshi@nic.in',
    employeeId: 'EMP-HFW-101',
    department: 'Health & Family Welfare Statistics',
    designation: 'Senior Medical Officer',
    role: 'Doctor',
    status: 'Active',
    coursesCompleted: 3,
    coursesInProgress: 1,
    avgAssessmentScore: 82,
    criticalGaps: ['Biostatistics & Clinical Trials'],
    joinedDate: '2023-04-10',
  },
  {
    id: 'emp-202',
    name: 'Ramesh K. Choudhary',
    email: 'ramesh.agri@nic.in',
    employeeId: 'EMP-AGRI-204',
    department: 'Agriculture & Farmers Welfare Statistics',
    designation: 'Agricultural Statistics Officer',
    role: 'Agricultural Statistics Officer',
    status: 'Active',
    coursesCompleted: 2,
    coursesInProgress: 2,
    avgAssessmentScore: 71,
    criticalGaps: ['Crop Yield Modeling', 'Remote Sensing GIS'],
    joinedDate: '2022-08-15',
  },
  {
    id: 'emp-203',
    name: 'Priyanka Ghosh',
    email: 'priyanka.ds@nic.in',
    employeeId: 'EMP-TECH-305',
    department: 'Technology, AI & Data Science Directorate',
    designation: 'Data Scientist',
    role: 'Data Scientist',
    status: 'Active',
    coursesCompleted: 4,
    coursesInProgress: 1,
    avgAssessmentScore: 88,
    criticalGaps: ['Machine Learning Interpretability'],
    joinedDate: '2023-01-20',
  },
  {
    id: 'emp-204',
    name: 'Kailash S. Rathore',
    email: 'kailash.nso@nic.in',
    employeeId: 'EMP-NSO-408',
    department: 'National Statistical Office (NSO)',
    designation: 'Statistical Officer',
    role: 'Statistical Officer',
    status: 'Active',
    coursesCompleted: 2,
    coursesInProgress: 2,
    avgAssessmentScore: 68,
    criticalGaps: ['NQAF Quality Audit', 'Stratified Sampling'],
    joinedDate: '2024-02-01',
  },
]

export const initialNotifications = [
  {
    id: 'notif-101',
    title: 'Mandatory Q3 Competency Gap Assessment',
    message: 'All officers across wings must complete their role competency benchmark evaluations before quarter close.',
    target: 'All Departments',
    type: 'Announcement',
    date: 'Today',
    readCount: 42,
  },
  {
    id: 'notif-102',
    title: 'New Clinical Data Governance Modules Available',
    message: 'Medical and healthcare officers can now access newly accredited epidemiology and clinical registry video curricula.',
    target: 'Health & Family Welfare Statistics',
    type: 'Update',
    date: 'Yesterday',
    readCount: 18,
  },
]
