// =============================================================================
// Skillstat AI - Admin Portal State & Mock Data Store
// Persists in localStorage for interactive CRUD operations
// =============================================================================

export const initialDepartments = [
  { id: 'dept-1', name: 'National Statistical Office (NSO)', head: 'Dr. R. K. Verma', employeeCount: 142, code: 'NSO-DEL' },
  { id: 'dept-2', name: 'Ministry of Statistics & PI (MoSPI)', head: 'Ms. Sunita Rao', employeeCount: 98, code: 'MOSPI-HQ' },
  { id: 'dept-3', name: 'State Directorates of Economics & Stats', head: 'Mr. Arvind Joshi', employeeCount: 215, code: 'DES-STATE' },
  { id: 'dept-4', name: 'Agriculture & Farmers Welfare Stats', head: 'Dr. Meenakshi Sundaram', employeeCount: 84, code: 'AGRI-STAT' },
  { id: 'dept-5', name: 'Health & Demographic Statistics Wing', head: 'Dr. P. Swaminathan', employeeCount: 65, code: 'HEALTH-DEMO' },
]

export const initialEmployees = [
  {
    id: 'emp-101',
    name: 'Vamshi Karshikalam',
    email: 'karshikalamvamshi34@gmail.com',
    employeeId: 'EMP-24018',
    department: 'National Statistical Office (NSO)',
    designation: 'Social Statistics Officer',
    role: 'Social Statistics Officer',
    status: 'Active',
    coursesCompleted: 4,
    coursesInProgress: 2,
    avgAssessmentScore: 78,
    criticalGaps: ['Data Quality Frameworks', 'AI/ML in Census'],
    joinedDate: '2023-04-15',
  },
  {
    id: 'emp-102',
    name: 'Pooja Sharma',
    email: 'pooja.sharma@nic.in',
    employeeId: 'EMP-21045',
    department: 'National Statistical Office (NSO)',
    designation: 'Senior Statistical Officer',
    role: 'Senior Statistical Officer',
    status: 'Active',
    coursesCompleted: 7,
    coursesInProgress: 1,
    avgAssessmentScore: 89,
    criticalGaps: ['Cloud Computing for Governance'],
    joinedDate: '2021-08-10',
  },
  {
    id: 'emp-103',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@gov.in',
    employeeId: 'EMP-19032',
    department: 'Ministry of Statistics & PI (MoSPI)',
    designation: 'Programme Statistics Officer',
    role: 'Programme Statistics Officer',
    status: 'Active',
    coursesCompleted: 3,
    coursesInProgress: 3,
    avgAssessmentScore: 65,
    criticalGaps: ['R for Survey Sampling', 'GIS Geospatial Analytics'],
    joinedDate: '2022-02-01',
  },
  {
    id: 'emp-104',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@nic.in',
    employeeId: 'EMP-23091',
    department: 'State Directorates of Economics & Stats',
    designation: 'District Statistical Officer',
    role: 'District Statistical Officer',
    status: 'Active',
    coursesCompleted: 5,
    coursesInProgress: 1,
    avgAssessmentScore: 82,
    criticalGaps: ['Big Data Indexing'],
    joinedDate: '2023-11-20',
  },
  {
    id: 'emp-105',
    name: 'Karthik Pillai',
    email: 'karthik.p@gov.in',
    employeeId: 'EMP-22078',
    department: 'Agriculture & Farmers Welfare Stats',
    designation: 'Agricultural Statistics Officer',
    role: 'Agricultural Statistics Officer',
    status: 'On Leave',
    coursesCompleted: 2,
    coursesInProgress: 1,
    avgAssessmentScore: 60,
    criticalGaps: ['Python Data Science', 'Remote Sensing Indices'],
    joinedDate: '2022-09-15',
  },
]

export const initialCourses = [
  {
    id: 'crs-1',
    title: 'Official Data Quality & Audit Frameworks',
    provider: 'iGOT Karmayogi',
    department: 'National Statistical Office (NSO)',
    competency: 'Data Quality Frameworks',
    duration: '6 Hours (Self-Paced)',
    enrolledCount: 184,
    completionRate: 85,
    status: 'Active',
    rating: 4.8,
  },
  {
    id: 'crs-2',
    title: 'Executive Geospatial Analysis with GIS',
    provider: 'NSSTA Workshop',
    department: 'All Departments',
    competency: 'GIS Geospatial Analytics',
    duration: '3 Days Residential',
    enrolledCount: 92,
    completionRate: 91,
    status: 'Active',
    rating: 4.9,
  },
  {
    id: 'crs-3',
    title: 'AI/ML Model Deployment in Public Governance',
    provider: 'iGOT Karmayogi',
    department: 'Ministry of Statistics & PI (MoSPI)',
    competency: 'AI/ML in Census',
    duration: '10 Hours',
    enrolledCount: 140,
    completionRate: 68,
    status: 'Active',
    rating: 4.7,
  },
  {
    id: 'crs-4',
    title: 'National Accounts & Price Index Estimation',
    provider: 'NSSTA Workshop',
    department: 'National Statistical Office (NSO)',
    competency: 'Economic Modeling',
    duration: '5 Days Workshop',
    enrolledCount: 110,
    completionRate: 94,
    status: 'Active',
    rating: 4.9,
  },
  {
    id: 'crs-5',
    title: 'Python for Statistical Computing & Survey Processing',
    provider: 'iGOT Karmayogi',
    department: 'All Departments',
    competency: 'Python Data Science',
    duration: '12 Hours',
    enrolledCount: 230,
    completionRate: 74,
    status: 'Active',
    rating: 4.8,
  },
]

export const initialSkillGaps = [
  {
    skill: 'Data Quality Frameworks',
    domain: 'Statistical Competencies',
    department: 'National Statistical Office (NSO)',
    employeesDeficient: 46,
    avgProficiency: 48,
    targetBenchmark: 85,
    gap: 37,
    priority: 'Critical',
  },
  {
    skill: 'AI/ML in Census & Surveys',
    domain: 'Technical Competencies',
    department: 'Ministry of Statistics & PI (MoSPI)',
    employeesDeficient: 62,
    avgProficiency: 42,
    targetBenchmark: 80,
    gap: 38,
    priority: 'Critical',
  },
  {
    skill: 'GIS Geospatial Analytics',
    domain: 'Technical Competencies',
    department: 'State Directorates of Economics & Stats',
    employeesDeficient: 38,
    avgProficiency: 54,
    targetBenchmark: 75,
    gap: 21,
    priority: 'Moderate',
  },
  {
    skill: 'Cloud Data Architecture',
    domain: 'Technical Competencies',
    department: 'All Departments',
    employeesDeficient: 29,
    avgProficiency: 58,
    targetBenchmark: 70,
    gap: 12,
    priority: 'Low',
  },
  {
    skill: 'Python Survey Processing',
    domain: 'Domain Competencies',
    department: 'Agriculture & Farmers Welfare Stats',
    employeesDeficient: 51,
    avgProficiency: 45,
    targetBenchmark: 80,
    gap: 35,
    priority: 'Critical',
  },
]

export const initialNotifications = [
  {
    id: 'notif-1',
    title: 'NSSTA Workshop Registration Open for Q3',
    message: 'Nominations are now invited for the residential workshop on Executive Geospatial Analysis. Deadline is next Friday.',
    target: 'All Departments',
    date: 'Today at 09:30 AM',
    type: 'Announcement',
    readCount: 198,
  },
  {
    id: 'notif-2',
    title: 'Mandatory iGOT Course Completion Reminder',
    message: 'Officers with critical gaps in Data Quality Frameworks must complete the accredited module before APAR cycle.',
    target: 'National Statistical Office (NSO)',
    date: 'Yesterday at 03:15 PM',
    type: 'Reminder',
    readCount: 142,
  },
  {
    id: 'notif-3',
    title: 'Weekend Competency Assessment Challenge Live',
    message: 'The nationwide leaderboard test for Statistical Officers is active until Sunday 11:59 PM.',
    target: 'All Registered Staff',
    date: '2 days ago',
    type: 'Challenge',
    readCount: 260,
  },
]
